// 150 words — 30 days of 5-a-day. Each entry: word, part of speech,
// pronunciation, definition, example sentence.
const WORDS = [
  ["ubiquitous","adj","yoo-BIK-wih-tus","Present or found everywhere at the same time.","Smartphones have become ubiquitous in modern life."],
  ["ephemeral","adj","ih-FEM-er-ul","Lasting for a very short time.","The ephemeral beauty of cherry blossoms draws crowds each spring."],
  ["pragmatic","adj","prag-MAT-ik","Dealing with things sensibly and realistically.","She took a pragmatic approach to the budget cuts."],
  ["candid","adj","KAN-did","Truthful and straightforward; frank.","He gave a candid assessment of the team's weaknesses."],
  ["resilient","adj","rih-ZIL-yunt","Able to recover quickly from difficulties.","Small businesses proved remarkably resilient during the downturn."],

  ["meticulous","adj","muh-TIK-yuh-lus","Showing great attention to detail; very careful.","Her meticulous notes made the audit painless."],
  ["ambiguous","adj","am-BIG-yoo-us","Open to more than one interpretation; unclear.","The contract's wording was deliberately ambiguous."],
  ["catalyst","noun","KAT-uh-list","A person or thing that causes a change or event.","The merger was the catalyst for a complete rebrand."],
  ["nuance","noun","NOO-ahns","A subtle difference in meaning, expression, or sound.","He missed the nuance in her tone."],
  ["tenacious","adj","tuh-NAY-shus","Holding firmly to something; persistent.","A tenacious reporter finally uncovered the story."],

  ["eloquent","adj","EL-uh-kwent","Fluent and persuasive in speaking or writing.","Her eloquent closing argument swayed the jury."],
  ["obsolete","adj","ob-suh-LEET","No longer produced or used; out of date.","Fax machines are largely obsolete today."],
  ["scrutinize","verb","SKROO-tuh-nyze","To examine closely and critically.","Investors scrutinized every line of the report."],
  ["inevitable","adj","in-EV-ih-tuh-bul","Certain to happen; unavoidable.","With costs rising, a price increase was inevitable."],
  ["profound","adj","pruh-FOWND","Very great or intense; showing deep insight.","The book had a profound effect on how I work."],

  ["arbitrary","adj","AR-bih-trair-ee","Based on random choice rather than reason.","The deadline felt arbitrary and unfair."],
  ["coherent","adj","koh-HEER-unt","Logical and consistent; easy to understand.","We need a coherent strategy, not five separate plans."],
  ["diligent","adj","DIL-ih-junt","Showing persistent, careful effort in work.","Diligent record-keeping saved them in the audit."],
  ["imminent","adj","IM-uh-nunt","About to happen very soon.","The storm's arrival was imminent."],
  ["versatile","adj","VUR-suh-tul","Able to adapt to many different functions.","Olive oil is the most versatile item in my kitchen."],

  ["paradox","noun","PAIR-uh-doks","A statement that seems contradictory but may be true.","It's a paradox that spending money can save money."],
  ["intricate","adj","IN-trih-kut","Very detailed and complicated.","The watch had an intricate mechanism."],
  ["prudent","adj","PROO-dunt","Acting with care and thought for the future.","It's prudent to keep three months of savings."],
  ["conducive","adj","kun-DOO-siv","Making a certain outcome likely or possible.","Open offices aren't always conducive to deep work."],
  ["salient","adj","SAY-lee-unt","Most noticeable or important.","Let's focus on the salient points of the proposal."],

  ["mitigate","verb","MIT-ih-gayt","To make less severe or painful.","Insurance helps mitigate financial risk."],
  ["implicit","adj","im-PLIS-it","Implied though not directly expressed.","There was an implicit promise of promotion."],
  ["redundant","adj","rih-DUN-dunt","No longer needed; superfluous.","The third paragraph is redundant — cut it."],
  ["viable","adj","VY-uh-bul","Capable of working successfully; feasible.","Solar became a viable option once prices fell."],
  ["astute","adj","uh-STOOT","Having sharp judgement; shrewd.","An astute negotiator reads the room first."],

  ["candour","noun","KAN-der","The quality of being open and honest.","I appreciated her candour about the risks."],
  ["exacerbate","verb","ig-ZAS-er-bayt","To make a problem worse.","Ignoring the complaint only exacerbated it."],
  ["plausible","adj","PLAW-zuh-bul","Seeming reasonable or probable.","That's a plausible explanation, but unproven."],
  ["reciprocal","adj","rih-SIP-ruh-kul","Given or felt by each toward the other; mutual.","The two firms signed a reciprocal agreement."],
  ["subtle","adj","SUT-ul","So delicate or precise as to be hard to notice.","There's a subtle difference between the two shades."],

  ["autonomy","noun","aw-TON-uh-mee","The right or condition of self-government.","The team was given full autonomy over its roadmap."],
  ["benevolent","adj","buh-NEV-uh-lunt","Well meaning and kindly.","A benevolent donor funded the library."],
  ["concise","adj","kun-SYSE","Giving a lot of information clearly in few words.","Keep the summary concise — one page."],
  ["deferential","adj","def-uh-REN-shul","Showing polite respect.","He was deferential to the older engineers."],
  ["empirical","adj","em-PEER-ih-kul","Based on observation or experience, not theory.","We need empirical evidence, not opinions."],

  ["fastidious","adj","fas-TID-ee-us","Very attentive to detail; hard to please.","He was fastidious about the formatting."],
  ["galvanize","verb","GAL-vuh-nyze","To shock or excite someone into action.","The news galvanized the whole department."],
  ["hierarchy","noun","HY-uh-rar-kee","A system ranking people or things by status.","Flat companies still have an informal hierarchy."],
  ["impartial","adj","im-PAR-shul","Treating all rivals equally; fair.","An impartial mediator reviewed both claims."],
  ["juxtapose","verb","JUK-stuh-pohz","To place close together for contrasting effect.","The film juxtaposes wealth and poverty."],

  ["lucid","adj","LOO-sid","Expressed clearly; easy to understand.","A lucid explanation of a complex topic."],
  ["mundane","adj","mun-DAYN","Lacking interest or excitement; ordinary.","Most of the job is mundane admin."],
  ["notorious","adj","noh-TOR-ee-us","Famous for something bad.","The route is notorious for traffic."],
  ["obsolescence","noun","ob-suh-LES-uns","The process of becoming outdated.","Planned obsolescence keeps people buying."],
  ["poignant","adj","POYN-yunt","Evoking a keen sense of sadness or regret.","A poignant farewell letter."],

  ["quintessential","adj","kwin-tuh-SEN-shul","Representing the most perfect example of a quality.","He's the quintessential all-rounder."],
  ["rhetoric","noun","RET-uh-rik","Persuasive speaking or writing; language that lacks sincerity.","The speech was heavy on rhetoric, light on detail."],
  ["scrupulous","adj","SKROO-pyuh-lus","Very careful about doing what is right.","She was scrupulous about expenses."],
  ["transient","adj","TRAN-zee-unt","Lasting only a short time.","The pain was transient and passed quickly."],
  ["unprecedented","adj","un-PRES-ih-den-tid","Never done or known before.","Demand reached unprecedented levels."],

  ["vindicate","verb","VIN-dih-kayt","To clear of blame; to prove right.","The results vindicated her decision."],
  ["wary","adj","WAIR-ee","Feeling caution about possible danger.","Be wary of deals that seem too good."],
  ["zealous","adj","ZEL-us","Showing great energy for a cause.","A zealous advocate for clean air."],
  ["aesthetic","adj","es-THET-ik","Concerned with beauty or appearance.","The app has a minimal aesthetic."],
  ["bolster","verb","BOHL-ster","To support or strengthen.","New data bolstered their argument."],

  ["clandestine","adj","klan-DES-tin","Kept secret, especially because illicit.","A clandestine meeting after hours."],
  ["debilitating","adj","dih-BIL-ih-tay-ting","Making someone very weak or infirm.","A debilitating illness kept him home."],
  ["enigmatic","adj","en-ig-MAT-ik","Difficult to interpret; mysterious.","She gave an enigmatic smile."],
  ["formidable","adj","FOR-mih-duh-bul","Inspiring fear or respect through size or skill.","A formidable opponent in negotiations."],
  ["gratuitous","adj","gruh-TOO-ih-tus","Done without good reason; uncalled for.","The film's gratuitous length hurt it."],

  ["hindsight","noun","HYND-syte","Understanding a situation only after it has happened.","In hindsight, we should have waited."],
  ["idiosyncratic","adj","id-ee-oh-sin-KRAT-ik","Peculiar to an individual.","His idiosyncratic filing system baffled everyone."],
  ["jargon","noun","JAR-gun","Special words used by a profession, hard for others.","Cut the jargon from the customer email."],
  ["laconic","adj","luh-KON-ik","Using very few words.","His laconic reply was simply: 'Fine.'"],
  ["magnanimous","adj","mag-NAN-ih-mus","Generous or forgiving, especially toward a rival.","She was magnanimous in victory."],

  ["negligible","adj","NEG-lih-juh-bul","So small as to be not worth considering.","The cost difference was negligible."],
  ["ostensible","adj","oh-STEN-sih-bul","Stated as true but perhaps not so.","The ostensible reason was budget; the real one was politics."],
  ["placate","verb","PLAY-kayt","To make someone less angry.","He tried to placate the frustrated customer."],
  ["quandary","noun","KWON-duh-ree","A state of uncertainty over a difficult choice.","I'm in a quandary about which offer to take."],
  ["reticent","adj","RET-ih-sunt","Not revealing one's thoughts readily.","He was reticent about his plans."],

  ["sporadic","adj","spuh-RAD-ik","Occurring at irregular intervals.","Sporadic rain all afternoon."],
  ["tangible","adj","TAN-juh-bul","Perceptible by touch; clear and definite.","We need tangible results this quarter."],
  ["ubiquity","noun","yoo-BIK-wih-tee","The state of being everywhere at once.","The ubiquity of screens changed childhood."],
  ["venerable","adj","VEN-er-uh-bul","Accorded great respect because of age or wisdom.","A venerable institution founded in 1820."],
  ["whimsical","adj","WIM-zih-kul","Playfully quaint or fanciful.","The shop had a whimsical window display."],

  ["abate","verb","uh-BAYT","To become less intense or widespread.","The storm finally began to abate."],
  ["brevity","noun","BREV-ih-tee","Concise and exact use of words.","Brevity is a kindness to your reader."],
  ["cursory","adj","KUR-suh-ree","Hasty and therefore not thorough.","A cursory glance missed the error."],
  ["dearth","noun","DURTH","A scarcity or lack of something.","There's a dearth of good candidates."],
  ["elicit","verb","ih-LIS-it","To draw out a response or reaction.","The question elicited an honest answer."],

  ["furtive","adj","FUR-tiv","Attempting to avoid notice; secretive.","A furtive glance at his phone."],
  ["garrulous","adj","GAIR-uh-lus","Excessively talkative about trivial matters.","A garrulous neighbour kept me an hour."],
  ["harbinger","noun","HAR-bin-jer","A sign of something to come.","Falling orders were a harbinger of trouble."],
  ["innocuous","adj","ih-NOK-yoo-us","Not harmful or offensive.","An innocuous comment somehow started a fight."],
  ["judicious","adj","joo-DISH-us","Having or showing good judgement.","Judicious use of the budget got us through."],

  ["keen","adj","KEEN","Highly developed; eager and enthusiastic.","She has a keen eye for detail."],
  ["lament","verb","luh-MENT","To express sorrow or regret about.","He lamented the loss of the old building."],
  ["myriad","noun","MEER-ee-ud","A countless or extremely great number.","A myriad of options made choosing hard."],
  ["nonchalant","adj","non-shuh-LAHNT","Feeling or appearing casually calm.","He was nonchalant about the deadline."],
  ["opaque","adj","oh-PAYK","Not able to be seen through; hard to understand.","The pricing model is completely opaque."],

  ["pervasive","adj","per-VAY-siv","Spreading widely throughout an area or group.","A pervasive sense of optimism."],
  ["quell","verb","KWEL","To put an end to, typically by force.","The statement quelled the rumours."],
  ["rudimentary","adj","roo-dih-MEN-tuh-ree","Involving basic principles; limited.","I have only rudimentary Spanish."],
  ["stoic","adj","STOH-ik","Enduring pain or hardship without showing feelings.","He was stoic about the setback."],
  ["trivial","adj","TRIV-ee-ul","Of little value or importance.","Don't waste the meeting on trivial items."],

  ["unilateral","adj","yoo-nih-LAT-er-ul","Performed by one side only.","A unilateral decision annoyed the partners."],
  ["vacillate","verb","VAS-uh-layt","To waver between different opinions.","She vacillated for weeks before deciding."],
  ["wane","verb","WAYN","To decrease in vigour or extent.","Interest in the product began to wane."],
  ["yield","verb","YEELD","To produce or provide; to give way.","The experiment yielded surprising results."],
  ["zenith","noun","ZEE-nith","The time at which something is most powerful.","The band was at its zenith in 1994."],

  ["affable","adj","AF-uh-bul","Friendly, good-natured, easy to talk to.","An affable host who put everyone at ease."],
  ["banal","adj","buh-NAHL","So lacking in originality as to be boring.","The speech was full of banal platitudes."],
  ["cogent","adj","KOH-junt","Clear, logical, and convincing.","She made a cogent case for the change."],
  ["disparate","adj","DIS-puh-rut","Essentially different in kind.","The report pulls together disparate sources."],
  ["ebullient","adj","ih-BUL-yunt","Cheerful and full of energy.","He was ebullient after the win."],

  ["frugal","adj","FROO-gul","Sparing or economical with money or food.","Frugal habits built her savings."],
  ["gregarious","adj","grih-GAIR-ee-us","Fond of company; sociable.","A gregarious colleague who knows everyone."],
  ["hapless","adj","HAP-lis","Unfortunate; unlucky.","The hapless intern got blamed for it."],
  ["insidious","adj","in-SID-ee-us","Proceeding harmfully in a subtle way.","Burnout is insidious — it creeps up."],
  ["jubilant","adj","JOO-bih-lunt","Feeling or expressing great happiness.","A jubilant crowd filled the square."],

  ["lethargic","adj","luh-THAR-jik","Sluggish and apathetic.","I feel lethargic after a big lunch."],
  ["mercurial","adj","mer-KYOOR-ee-ul","Subject to sudden changes of mood.","A brilliant but mercurial manager."],
  ["novel","adj","NOV-ul","New or unusual in an interesting way.","A novel approach to an old problem."],
  ["obstinate","adj","OB-stih-nut","Stubbornly refusing to change one's opinion.","He was obstinate about the deadline."],
  ["pertinent","adj","PUR-tih-nunt","Relevant to the matter at hand.","Only pertinent details, please."],

  ["quaint","adj","KWAYNT","Attractively unusual or old-fashioned.","A quaint village with cobbled streets."],
  ["robust","adj","roh-BUST","Strong and healthy; able to withstand stress.","A robust system that handles failures well."],
  ["succinct","adj","suk-SINKT","Briefly and clearly expressed.","Her succinct summary saved us an hour."],
  ["tedious","adj","TEE-dee-us","Too long, slow, or dull.","Data entry is tedious but necessary."],
  ["urbane","adj","ur-BAYN","Courteous and refined in manner.","An urbane guest who charmed the table."],

  ["vivid","adj","VIV-id","Producing powerful feelings or clear images.","A vivid description of the coast."],
  ["wistful","adj","WIST-ful","Having a feeling of vague longing.","A wistful look at old photographs."],
  ["adept","adj","uh-DEPT","Very skilled or proficient at something.","She's adept at defusing tension."],
  ["belie","verb","bih-LY","To fail to give a true impression of.","His calm voice belied his nerves."],
  ["copious","adj","KOH-pee-us","Abundant in supply or quantity.","She took copious notes."],

  ["dubious","adj","DOO-bee-us","Hesitating or doubting; not to be relied upon.","I'm dubious about those figures."],
  ["earnest","adj","UR-nist","Resulting from intense conviction; serious.","An earnest attempt to fix the problem."],
  ["fickle","adj","FIK-ul","Changing frequently, especially in loyalties.","Consumer taste is fickle."],
  ["glean","verb","GLEEN","To gather information bit by bit.","We gleaned a lot from the interviews."],
  ["hone","verb","HOHN","To refine or perfect over time.","He honed his pitch over fifty meetings."],

  ["impetus","noun","IM-pih-tus","The force that makes something happen.","The grant gave the project new impetus."],
  ["jovial","adj","JOH-vee-ul","Cheerful and friendly.","A jovial atmosphere in the office."],
  ["kindle","verb","KIN-dul","To arouse or inspire an emotion.","The trip kindled her interest in design."],
  ["languish","verb","LANG-gwish","To fail to make progress; grow weak.","The proposal languished for months."],
  ["myopic","adj","my-OH-pik","Lacking foresight or long-term thinking.","Cutting R&D was a myopic decision."],

  ["nadir","noun","NAY-deer","The lowest or most unsuccessful point.","1998 was the nadir of the company's fortunes."],
  ["obfuscate","verb","OB-fus-kayt","To deliberately make something unclear.","The jargon seemed designed to obfuscate."],
  ["panacea","noun","pan-uh-SEE-uh","A solution for all problems.","Automation is useful, but it's no panacea."],
  ["reprieve","noun","rih-PREEV","A cancellation or postponement of punishment.","The funding gave the project a reprieve."],
  ["staunch","adj","STAWNCH","Very loyal and committed in attitude.","A staunch supporter of the proposal."],

  ["taciturn","adj","TAS-ih-turn","Reserved; saying little.","Our taciturn colleague surprised us with a speech."],
  ["untenable","adj","un-TEN-uh-bul","Not able to be defended against attack.","His position became untenable after the leak."],
  ["voracious","adj","vuh-RAY-shus","Wanting great quantities of something.","A voracious reader — three books a week."],
  ["wanton","adj","WON-tun","Deliberate and unprovoked; reckless.","Wanton disregard for the safety rules."],
  ["ameliorate","verb","uh-MEEL-yuh-rayt","To make a bad situation better.","Small changes ameliorated the worst delays."]
];
